### ISSUE TITLE
not able to download weight

### ISSUE THREAD

**Issue by HHIR** [JavisPeng/FaceRecognitionWithMask#1]
as I dont have chinese number, I not able to register in baiduyun website.
can you please upload weight file somewhere else?

**Comment by ThanhPham1987** [comment]
hi @JavisPeng 
Can you upload model into google drive?
Best regards,
peterPham

**Comment by JavisPeng** [comment]
@ThanhPham1987  @HHIR
Sorry, I can not have access to  google drive, but you can down load free from https://wws.lanzous.com/igD2Ymgphfa
