### ISSUE TITLE
请问我想同时多个人脸一起识别，应该如何修改代码呢？

### ISSUE THREAD

**Issue by albertyou2** [JavisPeng/FaceRecognitionWithMask#2]
你好@JavisPeng

 这个项目识别率挺准的! 就是想请问下如果多人同时出现在视频中，能否同时识别出来，我发现好像一次智能识别一个

**Comment by JavisPeng** [comment]
只识别离摄像头最近的人脸，这是我们打卡项目需求，如果想同时识别多个
首先去掉box面积最大的判断，返回所有符合条件的box
https://github.com/JavisPeng/FaceRecognitionWithMask/blob/a8dc35b2ee851d57e02674d78bd7f704bba0ad47/face_detector.py#L57
然后在识别人脸函数中依次遍历所有的box即可
https://github.com/JavisPeng/FaceRecognitionWithMask/blob/a8dc35b2ee851d57e02674d78bd7f704bba0ad47/face_recognizer.py#L81

**Comment by albertyou2** [comment]
谢谢，我明白了
